# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 01:53
from __future__ import unicode_literals

import birds.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('', 'Undetermined'), ('F', 'Female'), ('M', 'Male')], default='Undetermined', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('', 'Unknown'), ('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=birds.models.bird_directory_path)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_imported', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.AreaLocation')),
            ],
        ),
        migrations.CreateModel(
            name='BirdExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='birds.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='BirdSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', 'Unknown'), ('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Undetermined'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('verification', models.CharField(blank=True, choices=[('', '(-) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='', max_length=1)),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birds.Bird')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='sightings.Sighting')),
            ],
        ),
    ]
