# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 01:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        ('locations', '0001_initial'),
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Approximate age (years)')),
                ('family', models.CharField(blank=True, max_length=200)),
                ('date_caught', models.DateField(blank=True, null=True)),
                ('caught_by', models.CharField(blank=True, max_length=200)),
                ('banded_by', models.CharField(blank=True, max_length=200)),
                ('caught_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('transmitter_channel', models.CharField(blank=True, max_length=10)),
                ('health', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('band', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.PrimaryLocation')),
                ('secondary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.SecondaryLocation')),
            ],
        ),
        migrations.CreateModel(
            name='BirdSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('banded', models.CharField(blank=True, choices=[('', "Couldn't tell"), ('U', 'Banded, unreadable'), ('B', 'Banded, readable'), ('N', 'Not banded')], default='N', max_length=1)),
                ('colour_band_type', models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic (modern)'), ('M', 'Metal (historic)')], default='', max_length=1, verbose_name='Colour band type')),
                ('colour_band_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('GREY', 'Grey'), ('O', 'Other')], default='', max_length=8)),
                ('colour_band_symbol', models.CharField(blank=True, max_length=1)),
                ('colour_band_symbol_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8)),
                ('verification', models.CharField(blank=True, choices=[('', 'Unverified'), ('Q', 'Questionable'), ('G', 'Good'), ('C', 'Confirmed')], default='', max_length=1)),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birds.Bird')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='sightings.Sighting')),
            ],
        ),
    ]
