# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 00:17
from __future__ import unicode_literals

import birds.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sightings', '0001_initial'),
        ('bands', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=birds.models.bird_directory_path)),
                ('health', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('band_combo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.BandCombo')),
                ('home_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.HomeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='BirdSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('verification', models.CharField(blank=True, choices=[('', '(-) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='', max_length=1)),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birds.Bird')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='sightings.Sighting')),
            ],
        ),
    ]
