# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
