# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('life_stage', models.CharField(blank=True, choices=[('', 'Unknown'), ('A', 'Adult'), ('S', 'Sub-adult'), ('J', 'Juvenile'), ('F', 'Fledgling')], default='', max_length=1)),
                ('banded', models.CharField(blank=True, choices=[('', "Couldn't tell"), ('U', 'Banded, unreadable'), ('B', 'Banded, readable'), ('N', 'Not banded')], default='N', max_length=1)),
                ('colour_band_type', models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic (modern)'), ('M', 'Metal (historic)')], default='', max_length=1, verbose_name='Colour band type')),
                ('colour_band_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('GREY', 'Grey')], default='', max_length=8)),
                ('colour_band_symbol', models.CharField(blank=True, max_length=1)),
                ('colour_band_symbol_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('GREY', 'Grey')], default='', max_length=8)),
                ('verification', models.CharField(blank=True, choices=[('', 'Unverified'), ('Q', 'Questionable'), ('G', 'Good'), ('C', 'Confirmed')], default='', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='bird',
            name='id_band_type',
        ),
        migrations.AddField(
            model_name='bird',
            name='colour_band_type',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic (modern)'), ('M', 'Metal (historic)')], default='', max_length=1, verbose_name='Colour band type'),
        ),
        migrations.AddField(
            model_name='birdsighting',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birds.Bird'),
        ),
        migrations.AddField(
            model_name='birdsighting',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightings.Sighting'),
        ),
    ]
