# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='date_updated',
            new_name='date_changed',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='band_combo',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='health',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='home_location',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='life_stage',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='photo',
        ),
        migrations.AddField(
            model_name='bird',
            name='date_imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
