# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 02:41
from __future__ import unicode_literals

import birds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=birds.models.bird_directory_path),
        ),
    ]
