# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.AreaLocation'),
        ),
    ]
