# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20160824_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='colour_band_colour',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('GREY', 'Grey'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='bird',
            name='colour_band_symbol_colour',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='colour_band_colour',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('GREY', 'Grey'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='colour_band_symbol_colour',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8),
        ),
    ]
