# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_bird_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsighting',
            name='verification',
            field=models.CharField(blank=True, choices=[('', '(-) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='', max_length=1),
        ),
    ]
