# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:13
from __future__ import unicode_literals

import birds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20170124_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=birds.models.bird_directory_path),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
