# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20160829_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='transmitter',
        ),
        migrations.AlterField(
            model_name='bird',
            name='id_band',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID band (v-band)'),
        ),
    ]
