# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20161117_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='family',
        ),
        migrations.AddField(
            model_name='bird',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
