# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20170124_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='birds.Bird')),
            ],
        ),
    ]
