# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_birdextended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Undetermined'), ('F', 'Female'), ('M', 'Male')], default='Undetermined', max_length=1),
        ),
        migrations.AlterField(
            model_name='bird',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Undetermined'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1),
        ),
    ]
