# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20160915_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsighting',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birds.Bird'),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='sightings.Sighting'),
        ),
    ]
