# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_remove_bird_transmitter_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='band',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='id_band',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='id_band_leg',
        ),
        migrations.RemoveField(
            model_name='birdsighting',
            name='band_type',
        ),
        migrations.AddField(
            model_name='birdsighting',
            name='band_style',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic'), ('UM', 'Metal (uncoated)'), ('CM', 'Metal (powder coated)')], default='', max_length=1, verbose_name='Colour band type'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='status',
            field=models.CharField(blank=True, choices=[('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='band_colour',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('LIME', 'Lime'), ('METAL', 'Metal'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='birdsighting',
            name='status',
            field=models.CharField(blank=True, choices=[('+', 'Alive'), ('-', 'Dead')], default='A', max_length=1),
        ),
    ]
