# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20161121_1320'),
        ('birds', '0008_auto_20161117_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='band_combo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.BandCombo'),
        ),
    ]
