# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandCombo',
            fields=[
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='birds.Bird')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
