# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20170621_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcombo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
