# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20170627_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcombo',
            name='style',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new')], default='old', max_length=3),
        ),
    ]
