# Generated by Django 2.0.1 on 2018-01-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20170627_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcombo',
            name='study_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.StudyArea'),
        ),
    ]
