# Generated by Django 2.1.7 on 2019-02-13 00:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20180118_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcombo',
            name='colours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='bandcombo',
            name='symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
