# Generated by Django 2.2.2 on 2019-06-17 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_gridtile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(blank=True, choices=[('', ''), ('tunnel', 'Tracking Tunnel Check'), ('fwf', 'FWF Hunting'), ('guide', 'Adventure Guiding'), ('trap', 'Pest Trapping'), ('permolat', 'Permolat/Remote Hut Work'), ('tramp', 'Tramping'), ('hunt', 'Hunting'), ('research', 'Researching'), ('other', 'Other')], default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('max_flock_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)')], default='new', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('observer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='surveys.Observer')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField()),
                ('kea', models.BooleanField(default=False)),
                ('activity', models.CharField(choices=[('W', 'W - Walking'), ('S', 'S - Stationary'), ('C', 'C - At camp (tent)'), ('H', 'H - At human structure (hut, carpark)'), ('X', 'X - Not surveying')], default='', max_length=1)),
                ('grid_tile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours', to='locations.GridTile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='surveys.Survey')),
            ],
        ),
    ]
