# Generated by Django 2.2.2 on 2019-06-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190624_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyhour',
            name='grid_tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hours', to='locations.GridTile'),
        ),
    ]
