# Generated by Django 2.2.9 on 2020-01-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190627_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='surveyhour',
            options={'ordering': ['survey', 'hour']},
        ),
    ]
