# Generated by Django 3.0.3 on 2020-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200119_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('tunnel', 'Tracking Tunnel Check'), ('fwf', 'FWF Hunting'), ('hunt', 'Hunting'), ('guide', 'Guiding'), ('trap', 'Trapping'), ('permolat', 'Permolat/Hut/Track Work'), ('tramp', 'Tramping'), ('research', 'Researching'), ('kea', 'Kea Surveying'), ('hut', 'Hut Wardening'), ('other', 'Other')], default='', max_length=15),
        ),
    ]
