# Generated by Django 3.0.3 on 2020-03-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='purpose',
        ),
    ]
