# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
