# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('study_areas', models.ManyToManyField(to='locations.StudyArea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
