# Generated by Django 2.0.3 on 2018-06-07 05:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_commonlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('feat_type', models.CharField(blank=True, max_length=200, null=True)),
                ('land_district', models.CharField(blank=True, max_length=200, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
