# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 04:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
