# Generated by Django 2.1.7 on 2019-02-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_region_polygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonLocation',
        ),
    ]
