# Generated by Django 2.2.2 on 2019-06-12 00:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_delete_commonlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridTile',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('min', django.contrib.gis.db.models.fields.PointField(srid=2193)),
                ('max', django.contrib.gis.db.models.fields.PointField(srid=2193)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
