# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, choices=[('', 'Undetermined'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('', 'Unknown'), ('+', 'Alive'), ('-', 'Dead')], default='', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_imported', models.DateTimeField(blank=True, null=True)),
                ('study_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.StudyArea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
