# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdExtended',
            fields=[
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bird_extended', serialize=False, to='birds.Bird')),
                ('is_extended', models.BooleanField(default=True, editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['bird'],
                'verbose_name': 'Extended Bird',
            },
        ),
    ]
