# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:21
from __future__ import unicode_literals

import birds.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_birdextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdextended',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=birds.models.bird_directory_path),
        ),
        migrations.AddField(
            model_name='birdextended',
            name='profile_picture_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
