# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20170625_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='study_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='locations.StudyArea'),
        ),
    ]
