# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20170627_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('undetermined', 'Undetermined')], default='undetermined', max_length=15),
        ),
        migrations.AlterField(
            model_name='bird',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('alive', 'Alive'), ('dead', 'Dead')], default='unknown', max_length=15),
        ),
    ]
