# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20170706_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdextended',
            name='profile_picture_attribution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
