# Generated by Django 2.0.1 on 2018-01-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_birdextended_profile_picture_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='study_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birds', to='locations.StudyArea'),
        ),
    ]
