# Generated by Django 2.0.3 on 2018-03-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_auto_20180118_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='primary_band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
