# Generated by Django 3.0.11 on 2021-03-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_bird_primary_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='gid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
