# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 03:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('style', models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic'), ('M', 'Metal')], default='', max_length=2)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='ID band must be a lowercase series of letters or numbers followed by a dash then a series of numbers. No spaces.', regex='^[a-z0-9]{1,2}-[0-9]+$')])),
                ('size', models.CharField(blank=True, choices=[('', 'Unspecified'), ('SM', 'Small'), ('LG', 'Large')], default='', max_length=2)),
                ('colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('UNCOLOURED', 'Uncoloured'), ('O', 'Other'), ('Colours', (('BLACK', 'Black'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('LIME', 'Lime'), ('METAL', 'Metal'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow')))], default='', max_length=10)),
                ('position', models.CharField(blank=True, choices=[('', 'Unknown'), ('S', 'Single'), ('T', 'Top'), ('B', 'Bottom')], default='', max_length=1)),
                ('leg', models.CharField(blank=True, choices=[('', 'Unknown'), ('L', 'Left'), ('R', 'Right')], default='', max_length=1)),
                ('symbol_colour', models.CharField(blank=True, choices=[('', 'Unspecified'), ('O', 'Other'), ('Colours', (('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('YELLOW', 'Yellow')))], default='', max_length=10)),
                ('symbol', models.CharField(blank=True, choices=[('', 'Unspecified'), ('Numbers', (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'))), ('Alphabet', (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z'))), ('Characters', (('!', '!'), ('"', '"'), ('#', '#'), ('$', '$'), ('%', '%'), ('&', '&'), ("'", "'"), ('(', '('), (')', ')'), ('*', '*'), ('+', '+'), (',', ','), ('-', '-'), ('.', '.'), ('/', '/'), (':', ':'), (';', ';'), ('<', '<'), ('=', '='), ('>', '>'), ('?', '?'), ('@', '@'), ('[', '['), ('\\', '\\'), (']', ']'), ('^', '^'), ('_', '_'), ('`', '`'), ('{', '{'), ('|', '|'), ('}', '}'), ('~', '~'))), ('Greek', (('obelus', 'Divide'), ('theta', 'Theta')))], default='', max_length=10)),
                ('band_type', models.CharField(choices=[('N', 'Letter (New)'), ('O', 'Colour (Old)'), ('M', 'Identifier (Metal)')], editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BandCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_type', models.CharField(choices=[('N', 'Letter (New)'), ('O', 'Colour (Old)')], default='N', max_length=1)),
                ('display', models.CharField(editable=False, max_length=255)),
                ('area_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.AreaLocation')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='band_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.BandCombo'),
        ),
        migrations.AlterUniqueTogether(
            name='band',
            unique_together=set([('style', 'identifier', 'colour', 'leg', 'position', 'symbol_colour', 'symbol', 'size')]),
        ),
    ]
