# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 01:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_band_leg', models.CharField(blank=True, choices=[('', 'Unknown'), ('L', 'Left'), ('R', 'Right')], default='', max_length=1, verbose_name='ID band leg (primary)')),
                ('id_band', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='ID band must be a lowercase series of letters or numbers followed by a dash then a series of numbers. No spaces.', regex='^[a-z0-9]{1,2}-[0-9]+$')], verbose_name='ID band (v-band)')),
                ('colour_band_type', models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic (modern)'), ('M', 'Metal (historic)')], default='', max_length=1, verbose_name='Colour band type')),
                ('colour_band_symbol_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8)),
                ('colour_band_symbol', models.CharField(blank=True, max_length=1)),
                ('colour_band_colour', models.CharField(blank=True, choices=[('', 'Unknown'), ('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('GREY', 'Grey'), ('O', 'Other')], default='', max_length=8)),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.PrimaryLocation')),
            ],
        ),
    ]
