# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_type', models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic (modern)'), ('M', 'Metal (historic)')], default='', max_length=1)),
                ('band_symbol_colour', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='WHITE', max_length=8)),
                ('band_symbol', models.CharField(max_length=1)),
                ('band_colour', models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('GREY', 'Grey'), ('O', 'Other')], default='BLACK', max_length=8)),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.PrimaryLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='band',
            unique_together=set([('band_symbol_colour', 'band_symbol', 'band_colour', 'primary_location')]),
        ),
    ]
