# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 02:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_symbol_colour',
            new_name='symbol_colour',
        ),
        migrations.AddField(
            model_name='band',
            name='colour',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('LIME', 'Lime'), ('METAL', 'Metal'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='BLACK', max_length=8),
        ),
        migrations.AddField(
            model_name='band',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='ID band must be a lowercase series of letters or numbers followed by a dash then a series of numbers. No spaces.', regex='^[a-z0-9]{1,2}-[0-9]+$')]),
        ),
        migrations.AddField(
            model_name='band',
            name='leg',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('L', 'Left'), ('R', 'Right')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='band',
            name='position',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('T', 'Top'), ('B', 'Bottom'), ('S', 'Single')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='band',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('SM', 'Small'), ('LG', 'Large')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='band',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic'), ('UM', 'Metal (uncoated)'), ('CM', 'Metal (powder coated)')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='band',
            name='symbol',
            field=models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('!', '!'), ('"', '"'), ('#', '#'), ('$', '$'), ('%', '%'), ('&', '&'), ("'", "'"), ('(', '('), (')', ')'), ('*', '*'), ('+', '+'), (',', ','), ('-', '-'), ('.', '.'), ('/', '/'), (':', ':'), (';', ';'), ('<', '<'), ('=', '='), ('>', '>'), ('?', '?'), ('@', '@'), ('[', '['), ('\\', '\\'), (']', ']'), ('^', '^'), ('_', '_'), ('`', '`'), ('{', '{'), ('|', '|'), ('}', '}'), ('~', '~'), ('obelus', 'Divide'), ('theta', 'Theta')], default='', max_length=10),
        ),
        migrations.RemoveField(
            model_name='band',
            name='band_type',
        ),
        migrations.AlterUniqueTogether(
            name='band',
            unique_together=set([('style', 'identifier', 'colour', 'leg', 'position', 'symbol', 'symbol_colour', 'size')]),
        ),
    ]
