# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandcombo',
            name='status',
        ),
    ]
