# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_band_band_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandcombo',
            name='display',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
