# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_homelocation'),
        ('bands', '0003_auto_20161117_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('+', 'Active'), ('-', 'Decommissioned')], default='+', max_length=1)),
                ('combo', models.CharField(choices=[('L', 'Letter Combo (New)'), ('C', 'Colour Combo (Old)')], default='L', max_length=1)),
                ('home_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.HomeLocation')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='primary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='colour',
            field=models.CharField(blank=True, choices=[('', ''), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('LIME', 'Lime'), ('METAL', 'Metal'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='band',
            name='symbol_colour',
            field=models.CharField(blank=True, choices=[('', ''), ('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('O', 'Other')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='band',
            name='sighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.BandCombo'),
        ),
    ]
