# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20161121_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='sighting',
            new_name='band_combo',
        ),
        migrations.RemoveField(
            model_name='bandcombo',
            name='combo',
        ),
        migrations.AddField(
            model_name='bandcombo',
            name='combo_type',
            field=models.CharField(choices=[('N', 'Letter (New)'), ('O', 'Colour (Old)')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='band',
            name='position',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('S', 'Single'), ('T', 'Top'), ('B', 'Bottom')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='band',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic'), ('UM', 'Metal (uncoloured)'), ('CM', 'Metal (coloured)')], default='', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='band',
            unique_together=set([('style', 'identifier', 'colour', 'leg', 'position', 'symbol_colour', 'symbol', 'size')]),
        ),
    ]
