# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_bandcombo_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandcombo',
            old_name='home_location',
            new_name='area_location',
        ),
        migrations.AlterField(
            model_name='bandcombo',
            name='display',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
