# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20161121_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='colour',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('UNCOLOURED', 'Uncoloured'), ('O', 'Other'), ('Colours', (('BLACK', 'Black'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('LIME', 'Lime'), ('METAL', 'Metal'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow')))], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='band',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('P', 'Plastic'), ('M', 'Metal')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='band',
            name='symbol',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('Numbers', (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'))), ('Alphabet', (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z'))), ('Characters', (('!', '!'), ('"', '"'), ('#', '#'), ('$', '$'), ('%', '%'), ('&', '&'), ("'", "'"), ('(', '('), (')', ')'), ('*', '*'), ('+', '+'), (',', ','), ('-', '-'), ('.', '.'), ('/', '/'), (':', ':'), (';', ';'), ('<', '<'), ('=', '='), ('>', '>'), ('?', '?'), ('@', '@'), ('[', '['), ('\\', '\\'), (']', ']'), ('^', '^'), ('_', '_'), ('`', '`'), ('{', '{'), ('|', '|'), ('}', '}'), ('~', '~'))), ('Greek', (('obelus', 'Divide'), ('theta', 'Theta')))], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='band',
            name='symbol_colour',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('O', 'Other'), ('Colours', (('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('YELLOW', 'Yellow')))], default='', max_length=10),
        ),
    ]
