# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20161122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcombo',
            name='combo_type',
            field=models.CharField(choices=[('N', 'Letter (New)'), ('O', 'Colour (Old)')], default='N', max_length=1),
        ),
    ]
