# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_remove_sighting_number_sighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
