# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sightings.models.media
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_commonlocation'),
        ('birds', '0005_auto_20170706_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingsBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banded', models.CharField(choices=[('unknown', "Couldn't tell"), ('unreadable', 'Banded, unreadable'), ('readable', 'Banded, readable'), ('unbanded', 'Not banded')], default='unknown', max_length=15)),
                ('band_combo', models.CharField(blank=True, max_length=200, null=True)),
                ('sex_guess', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=15, null=True)),
                ('life_stage_guess', models.CharField(blank=True, choices=[('fledgling', 'Fledgling'), ('juvenile', 'Juvenile'), ('sub-adult', 'Sub-Adult'), ('adult', 'Adult')], max_length=15, null=True)),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='birds.Bird')),
            ],
            options={
                'verbose_name': 'Bird sighting',
            },
        ),
        migrations.CreateModel(
            name='SightingsContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('activity', models.CharField(blank=True, choices=[('', ''), ('tourist', 'Tourist'), ('local', 'Local'), ('school', 'School Group'), ('community', 'Community Group'), ('skier', 'Skier'), ('tramper', 'Tramper'), ('hunter', 'Hunter'), ('birder', 'Birder'), ('doc', 'DOC Staff'), ('research', 'Researcher'), ('other', 'Other')], default='', max_length=15)),
                ('heard', models.CharField(blank=True, choices=[('', ''), ('shelter', 'Kea Information Shelter'), ('poster', 'Poster'), ('brochure', 'Brochure'), ('social', 'Social Media'), ('news', 'News'), ('friend', 'From a friend'), ('other', 'Other')], default='', max_length=15)),
                ('communications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'contributor',
            },
        ),
        migrations.CreateModel(
            name='SightingsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=sightings.models.media.sighting_directory_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'media',
                'verbose_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='SightingsNonSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sighted', models.DateField()),
                ('time_sighted', models.TimeField()),
                ('comments', models.TextField(blank=True)),
                ('quality', models.CharField(choices=[('-1', '(-1) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='-1', max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location_details', models.TextField()),
                ('expectations', models.TextField(blank=True)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sightings.SightingsContributor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region')),
            ],
            options={
                'verbose_name': 'Non-sighting',
            },
        ),
        migrations.CreateModel(
            name='SightingsSighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sighted', models.DateField()),
                ('time_sighted', models.TimeField()),
                ('comments', models.TextField(blank=True)),
                ('quality', models.CharField(choices=[('-1', '(-1) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='-1', max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sighting_type', models.CharField(choices=[('heard', 'Heard'), ('sighted', 'Sighted')], default='sighted', max_length=15)),
                ('point_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy', models.CharField(choices=[('estimated', 'Estimated, used map'), ('known', 'Known, used map'), ('gps', 'GPS coordinates')], default='estimated', max_length=15)),
                ('specificity', models.CharField(choices=[('general', 'Area (general)'), ('specific', 'Specific (point)')], default='general', max_length=15)),
                ('number', models.PositiveIntegerField()),
                ('behaviour', models.TextField(blank=True)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sightings.SightingsContributor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region')),
            ],
            options={
                'verbose_name': 'Sighting',
            },
        ),
        migrations.AddField(
            model_name='sightingsmedia',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sightings.SightingsSighting'),
        ),
        migrations.AddField(
            model_name='sightingsbird',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='sightings.SightingsSighting'),
        ),
    ]
