# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingssighting',
            name='location_details',
            field=models.TextField(blank=True),
        ),
    ]
