# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_sightingssighting_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingssighting',
            name='precision',
            field=models.PositiveIntegerField(choices=[(10, '(10m) GPS Coordinates'), (50, '(50m) Known Location'), (200, '(200m) Approximate Location'), (1000, '(1000m) General Area')], default=50),
        ),
    ]
