# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sightingssighting_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightingssighting',
            name='accuracy',
        ),
    ]
