# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_remove_sightingssighting_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightingssighting',
            name='specificity',
        ),
    ]
