# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_remove_sightingssighting_specificity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingsbird',
            name='life_stage_guess',
            field=models.CharField(blank=True, choices=[('', 'Unsure'), ('fledgling', 'Fledgling'), ('juvenile', 'Juvenile'), ('sub-adult', 'Sub-Adult'), ('adult', 'Adult')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sightingsbird',
            name='sex_guess',
            field=models.CharField(blank=True, choices=[('', 'Unsure'), ('female', 'Female'), ('male', 'Male')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='sighting_type',
            field=models.CharField(choices=[('sighted', 'Sighted'), ('heard', 'Heard')], default='sighted', max_length=15),
        ),
    ]
