# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20170724_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingssighting',
            name='sighting_type',
            field=models.CharField(choices=[('sighted', 'Sighted'), ('heard', 'Heard'), ('distant', 'Sighted (distant)')], default='sighted', max_length=15),
        ),
    ]
