# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20170725_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingssighting',
            name='precision',
            field=models.PositiveIntegerField(choices=[(10, '(10m) GPS Coordinates'), (50, '(50m) Known Location'), (200, '(200m) Approximate Location'), (1000, '(1000m) General Area')]),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='sighting_type',
            field=models.CharField(choices=[('sighted', 'Sighted'), ('heard', 'Heard'), ('distant', 'Sighted (distant)')], max_length=15),
        ),
    ]
