# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_auto_20170725_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingsbird',
            name='banded',
            field=models.CharField(choices=[('unknown', "Couldn't tell"), ('unreadable', 'Banded, unreadable'), ('readable', 'Banded, readable'), ('unbanded', 'Not banded')], max_length=15),
        ),
    ]
