# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0010_auto_20170728_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingsnonsighting',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Moderator: Add notes here if you needed to                                                   change sighting information (not public).'),
        ),
        migrations.AlterField(
            model_name='sightingsnonsighting',
            name='quality',
            field=models.CharField(choices=[('-1', '(-1) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='-1', help_text='Moderator: Select level of quality.                                           Confirmed should only be used for known contributors.', max_length=3),
        ),
        migrations.AlterField(
            model_name='sightingsnonsighting',
            name='region',
            field=models.ForeignKey(help_text='Moderator: Select region for sighting.', on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Moderator: Add notes here if you needed to                                                   change sighting information (not public).'),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='quality',
            field=models.CharField(choices=[('-1', '(-1) Unverified'), ('0', '(0) Bad'), ('1', '(1) OK'), ('2', '(2) Confirmed')], default='-1', help_text='Moderator: Select level of quality.                                           Confirmed should only be used for known contributors.', max_length=3),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='region',
            field=models.ForeignKey(help_text='Moderator: Select region for sighting.', on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
    ]
