# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0011_auto_20170808_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingssighting',
            name='revisit',
            field=models.BooleanField(default=False, help_text='Moderator: Tick this if this sighting needs                                              revisiting, e.g. for birds that are not in database.'),
        ),
    ]
