# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sightings.models.media
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_birdextended_profile_picture_attribution'),
        ('sightings', '0012_sightingssighting_revisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_image', versatileimagefield.fields.VersatileImageField(upload_to=sightings.models.media.sighting_directory_path)),
                ('sighting_image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('birds', models.ManyToManyField(to='birds.Bird', verbose_name='Birds in image')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sightings.SightingsSighting')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
            },
        ),
    ]
