# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0013_sightingsmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingsbird',
            name='revisit',
            field=models.BooleanField(default=False, help_text='Moderator: tick if bird not added yet'),
        ),
    ]
