# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0014_sightingsbird_revisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightingssighting',
            name='revisit',
        ),
    ]
