# Generated by Django 2.0.1 on 2018-01-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0016_auto_20171024_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingssighting',
            name='favourite',
            field=models.BooleanField(default=False, help_text='Moderator: If noteworthy sighting'),
        ),
        migrations.AlterField(
            model_name='sightingsbird',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='birds.Bird'),
        ),
    ]
