# Generated by Django 2.0.3 on 2018-03-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0017_auto_20180118_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sightingsmedia',
            options={'ordering': ['id'], 'verbose_name': 'media', 'verbose_name_plural': 'media'},
        ),
    ]
