# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0021_auto_20180610_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingsnonsighting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Region'),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Region'),
        ),
    ]
