# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0022_auto_20180610_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightingsnonsighting',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sightingssighting',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
