# Generated by Django 2.1.7 on 2019-02-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0023_auto_20180610_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SightingsContributor',
            new_name='Contributor',
        ),
    ]
