# Generated by Django 2.1.7 on 2019-02-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0024_auto_20190220_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SightingsNonSighting',
            new_name='NonSighting',
        ),
        migrations.RenameModel(
            old_name='SightingsSighting',
            new_name='Sighting',
        ),
    ]
