# Generated by Django 2.1.7 on 2019-03-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0027_sighting_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingImportReport',
            fields=[
            ],
            options={
                'verbose_name': 'Import report',
                'proxy': True,
                'indexes': [],
            },
            bases=('sightings.sighting',),
        ),
    ]
