# Generated by Django 2.1.7 on 2019-03-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0028_sightingimportreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='origin',
            new_name='import_id',
        ),
    ]
