# Generated by Django 2.1.7 on 2019-03-09 01:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0029_auto_20190309_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting')))], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting')))], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='import_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Import ID'),
        ),
    ]
