# Generated by Django 2.1.7 on 2019-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0030_auto_20190309_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Moderator: If confirmed (known contributor or photo evidence)'),
        ),
    ]
