# Generated by Django 2.1.7 on 2019-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0031_sighting_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonsighting',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='quality',
        ),
        migrations.AlterField(
            model_name='nonsighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
    ]
