# Generated by Django 2.2.2 on 2019-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0032_auto_20190309_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting'), ('captive', 'Captive Sighting')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('fwf', 'FWF Sighting'), ('kct', 'KCT Sighting'), ('captive', 'Captive Sighting')))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
    ]
