# Generated by Django 2.2.2 on 2019-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0033_auto_20190617_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='precision',
            field=models.PositiveIntegerField(choices=[(10, '(10m) GPS Coordinates'), (50, '(50m) Known Location'), (200, '(200m) Approximate Location'), (1000, '(1000m) General Area'), (5000, '(5000m) Educated Guess')]),
        ),
    ]
