# Generated by Django 3.0.3 on 2020-03-18 18:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0034_auto_20190909_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='import_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Import ID'),
        ),
    ]
