# Generated by Django 2.2.2 on 2019-06-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_gridtile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('max_flock_size', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('observer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='survey.Observer')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveIntegerField()),
                ('kea', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('W', '[W] Walking'), ('S', '[S] Stationary'), ('C', '[C] At camp (tent)'), ('H', '[H] At human structure (hut, carpark)'), ('-', '[-] Not surveying')], default='', max_length=1)),
                ('grid_tile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours', to='locations.GridTile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='survey.Survey')),
            ],
        ),
    ]
