# Generated by Django 2.2.2 on 2019-06-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
