# Generated by Django 2.2.2 on 2019-06-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190618_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)')], default='new', max_length=10),
        ),
    ]
