# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeLocation',
            new_name='AreaLocation',
        ),
    ]
